### ISSUE TITLE
Cash Field Value not cleared after sign-out

### ISSUE THREAD

**Issue by nivritii** [Raghuramgrr/vmcs#2]
1) Login to the VCMS
2) See the cash field - value is 20 (assume) 
3) Signout the VCMS
4) Sign in again 
5) Cash field holding the same value - Bug

**Comment by Raghuramgrr** [comment]
Issue observed by the QA.

Bug assigned to developer @cherrygu1209

**Comment by cherrygu1209** [comment]
I have already fixes the bugs in the file 'MaintenanceController.java'
I have uploaded it in the new brach which named as 'defect' branch.

**Comment by Raghuramgrr** [comment]
Assigned to QA for verification of the BUG  - @nivritii   will Verify the Fix 

package created and given to QA

**Comment by nivritii** [comment]
With the bug fix, the data is cash field resets after session.
Hence, verified bug fix.

**Comment by Raghuramgrr** [comment]
Issue closed

**Comment by Raghuramgrr** [comment]
Issue closed
